# This file was generated by GoReleaser. DO NOT EDIT.
cask "alpha" do
  version "4.189.0"

  on_macos do
    on_arm do
      sha256 "bc538b875dd08d5abfdcd1a26b386a834144b2d4f4cf1e0d6aa743fcc2c7e402"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d8ba67ed8264e88dfd4849e6a826d40c31a0f9e2165da3b61235b86bebe0ff37"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59fc4aa4c13ac374de2c10f15025e5778b2e9e0950a2df535f6304c2ffc8a918"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d91b591ae9aa32fd06fc20885a8afd106c035407cb57b99e88e1d8fc4f489ce1"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_linux_amd64.tar.gz"
    end
  end

  name "alpha"
  desc "Alpha Platform CLI"
  homepage "https://github.com/ASRRtechnologies/alpha-cli-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alpha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/alpha"]
    end
  end

  # No zap stanza required
end
