# This file was generated by GoReleaser. DO NOT EDIT.
cask "alpha" do
  version "4.74.3"

  on_macos do
    on_arm do
      sha256 "dfc6ee676c94eede5ac3624aa057dc9356acac364aa6165172367aa9fe52e119"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "133a16ed5c55ef08b8902b850972f251f332b33a5b821db00e60afd83cfc75fa"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9645f1f6e7c8aa5695a07525e15d896e9b615dba75e29ed7a4756d3b4cdaaf64"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bbc1cddc17e7a30d2cb5b472317521be3a9df6effc1bb733db35501619398150"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_linux_amd64.tar.gz"
    end
  end

  name "alpha"
  desc "Alpha Platform CLI"
  homepage "https://github.com/ASRRtechnologies/alpha-cli-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alpha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/alpha"]
    end
  end

  # No zap stanza required
end
