# This file was generated by GoReleaser. DO NOT EDIT.
cask "alpha" do
  version "4.74.5"

  on_macos do
    on_arm do
      sha256 "42561a0514db7e9d2d54998f9d7b739458e2d37379ae08a043ef004d478e89a0"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9980564f51db996a9b25caad7aa3b253019f1ea8b3ab533b2dc5e5eb53f4c221"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c270551e5ce55f26602a5a1c70c6864c9aad5bf3cae44827a62e6d92e9ee3f0f"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "911eb3cb81940aa434dc37ed4d8f3cf2289f8ad6c1c782e232f3c44a5c38f89c"
      url "https://github.com/ASRRtechnologies/alpha-cli-dist/releases/download/v#{version}/alpha_#{version}_linux_amd64.tar.gz"
    end
  end

  name "alpha"
  desc "Alpha Platform CLI"
  homepage "https://github.com/ASRRtechnologies/alpha-cli-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alpha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/alpha"]
    end
  end

  # No zap stanza required
end
